name: ESO Docker Image

on:
  workflow_dispatch:
    inputs:
      version_tag:
        default: latest
        required: true
        description: Image tag version
        type: string
      target_branch:
        default: develop
        required: true
        description: Branch from where the image going to be build
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          repository: 'thejurysays/external-secrets'
          ref: ${{ github.event.inputs.target_branch }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build secrets safe image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.standalone
          push: true
          tags: thejurysays/external-secrets:${{ github.event.inputs.version_tag }}
